// Procedural pixel art in a gothic alchemical palette. Owner: SPRITES worker. Browser only.
// Spec: PRODUCT.md §9. Every drawing is built from rows of palette characters ('.' = transparent).
const Sprites = {
  /** char -> CSS colour. Skin chars 's' (base) and 'S' (light) are replaced by TINTS. */
  PAL: {
    k: '#0b0710', d: '#2a1a33', p: '#4a2f5e', b: '#c9b58e', B: '#efe6c8',
    s: '#7fa07a', S: '#a9c49a', r: '#8e1b2b', R: '#d93a3a', g: '#3f8f7c', G: '#7fd0b5',
    m: '#b08a3a', M: '#e6c25a', o: '#f08a1e', O: '#ffd23f', w: '#e9e2f0', e: '#9ad13a', h: '#5a5a6a',
  },
  /** tint name -> { s, S } skin colour overrides. */
  TINTS: {
    default: { s: '#7fa07a', S: '#a9c49a' },
    verdigris: { s: '#3f8f7c', S: '#7fd0b5' },
    ash: { s: '#5a5a6a', S: '#9a9aa8' },
    blood: { s: '#8e1b2b', S: '#d93a3a' },
    gold: { s: '#b08a3a', S: '#e6c25a' },
  },

  /**
   * Build a canvas from rows of palette characters.
   * @param {string[]} rows equal-length strings; '.' is transparent
   * @param {Object<string,string>} [overrides] char -> colour replacing PAL entries
   * @returns {HTMLCanvasElement}
   */
  fromMap(rows, overrides) {
    const h = rows.length;
    const w = h ? rows[0].length : 0;
    const cv = document.createElement('canvas');
    cv.width = w;
    cv.height = h;
    const ctx = cv.getContext('2d');
    ctx.imageSmoothingEnabled = false;
    this._blit(ctx, rows, 0, 0, overrides);
    return cv;
  },

  /**
   * 16x16 tile or icon, cached. Names: floor, wall, fog, start, stairs, exit, trap, fire,
   * vial_vida, vial_frio, esencia, pergamino, enemy, heart, heat, energy, clock, skull, stump, card, table.
   * @param {string} name @returns {HTMLCanvasElement}
   */
  get(name) {
    const key = this._TILES[name] ? name : 'fog';
    if (!this._tiles[key]) {
      this._tiles[key] = this.fromMap(this._TILES[key], this._TILE_OVER[key]);
    }
    return this._tiles[key];
  },

  /**
   * 16x16 icon of a limb piece for lists (harvest, table, body strip), cached.
   * @param {string} spriteKey one of DATA.SPRITE_KEYS[*]
   * @returns {HTMLCanvasElement}
   */
  limb(spriteKey) {
    const piece = this._pieceByKey(spriteKey) || this._pieceByKey(this._fallbackKey(spriteKey));
    if (!this._limbs[piece.key]) {
      const cv = document.createElement('canvas');
      cv.width = 16;
      cv.height = 16;
      const ctx = cv.getContext('2d');
      ctx.imageSmoothingEnabled = false;
      const off = this._ICON_OFF[piece.type];
      this._blit(ctx, piece.rows, off.x, off.y, this.TINTS.default);
      this._limbs[piece.key] = cv;
    }
    return this._limbs[piece.key];
  },

  /**
   * 32x40 creature composed from limb pieces: legs at the bottom, torso above, head on top, arms at the
   * torso's sides. A null slot is drawn as a bandaged stump. Cached by (slots, tint).
   * @param {{head:string|null, torso:string|null, armL:string|null, armR:string|null, legL:string|null, legR:string|null}} slots limb ids (DATA.limbs) or null
   * @param {string} tint a TINTS key (unknown -> 'default')
   * @returns {HTMLCanvasElement}
   */
  creature(slots, tint) {
    const s = slots || {};
    const t = this.TINTS[tint] ? tint : 'default';
    const key = [s.head, s.torso, s.armL, s.armR, s.legL, s.legR, t].join('|');
    if (this._creatures[key]) return this._creatures[key];
    const cv = document.createElement('canvas');
    cv.width = 32;
    cv.height = 40;
    const ctx = cv.getContext('2d');
    ctx.imageSmoothingEnabled = false;
    const over = this.TINTS[t];
    const parts = this._CREATURE_PARTS;
    // Legs first, then arms, then torso, then head, so each layer covers the joint of the one below.
    for (let i = 0; i < parts.length; i++) {
      const p = parts[i];
      const piece = this._piece(s[p.slot], p.type);
      if (piece) this._blit(ctx, piece.rows, p.x, p.y, over);
      else this._blit(ctx, this._STUBS[p.type], p.sx, p.sy, over);
    }
    this._creatures[key] = cv;
    return cv;
  },

  // ---------------------------------------------------------------- private

  /** Pixel-perfect blit of a char map into a context. */
  _blit(ctx, rows, ox, oy, over) {
    for (let y = 0; y < rows.length; y++) {
      const row = rows[y];
      for (let x = 0; x < row.length; x++) {
        const ch = row.charAt(x);
        if (ch === '.') continue;
        const col = (over && over[ch]) || this.PAL[ch];
        if (!col) continue;
        ctx.fillStyle = col;
        ctx.fillRect(ox + x, oy + y, 1, 1);
      }
    }
  },

  /** 'head'|'torso'|'arm'|'leg' for a known sprite key, else null. */
  _typeOf(key) {
    if (!key) return null;
    const i = key.indexOf('_');
    if (i < 0) return null;
    return this._PIECES[key] ? key.slice(0, i) : null;
  },

  /** @returns {{key:string, type:string, rows:string[]}|null} null when the key is not a limb piece. */
  _pieceByKey(spriteKey) {
    const type = this._typeOf(spriteKey);
    return type ? { key: spriteKey, type: type, rows: this._PIECES[spriteKey] } : null;
  },

  /** Plainest sprite key of the same type as an unknown key. */
  _fallbackKey(spriteKey) {
    const t = String(spriteKey || '').split('_')[0];
    return this._FALLBACK[this._ICON_OFF[t] ? t : 'head'];
  },

  /**
   * Resolve a slot value (limb id from DATA.limbs, or null) to a limb piece. Falls back to the plainest
   * piece of the slot's type when DATA has no entry or names an unknown sprite.
   * @param {string|null} limbId @param {string} slotType 'head'|'torso'|'arm'|'leg'
   * @returns {{key:string, type:string, rows:string[]}|null} null when the slot is empty
   */
  _piece(limbId, slotType) {
    if (!limbId) return null;
    const lim = (typeof DATA !== 'undefined' && DATA.limbs) ? DATA.limbs[limbId] : null;
    const byKey = lim ? this._pieceByKey(lim.sprite) : null;
    return byKey || this._pieceByKey(this._FALLBACK[slotType] || this._FALLBACK.head);
  },

  _tiles: {},
  _limbs: {},
  _creatures: {},
  /** Where each piece sits inside its 16x16 list icon. */
  _ICON_OFF: {
    head: { x: 2, y: 2 }, torso: { x: 1, y: 0 }, arm: { x: 5, y: 1 }, leg: { x: 5, y: 2 },
  },
  /** Plainest sprite key of each type, used when a limb is unknown to DATA. */
  _FALLBACK: {
    head: 'head_skull', torso: 'torso_stitch', arm: 'arm_bone', leg: 'leg_bone',
  },
  /** Where each slot is drawn on the 32x40 creature, and where its stump goes. */
  _CREATURE_PARTS: [
    { slot: 'legL', type: 'leg', x: 9, y: 28, sx: 9, sy: 32 },
    { slot: 'legR', type: 'leg', x: 17, y: 28, sx: 17, sy: 32 },
    { slot: 'armL', type: 'arm', x: 3, y: 13, sx: 3, sy: 19 },
    { slot: 'armR', type: 'arm', x: 23, y: 13, sx: 23, sy: 19 },
    { slot: 'torso', type: 'torso', x: 9, y: 12, sx: 9, sy: 12 },
    { slot: 'head', type: 'head', x: 10, y: 0, sx: 12, sy: 6 },
  ],

  /** Fog is translucent so unseen cells read as a veil over whatever is below. */
  _TILE_OVER: {
    fog: { k: 'rgba(11,7,16,0.86)', d: 'rgba(42,26,51,0.86)' },
  },

  /** 16x16 room and UI tiles, keyed by get() name. */
  _TILES: {
    floor: [
      'kkkkkkkkkkkkkkkk',
      'kddddddddkdddddk',
      'kddddddddkdddddk',
      'kdddpddddkddpddk',
      'kddddddddkdddddk',
      'kdddppdddkdddddk',
      'kddddddddkdddpdk',
      'kddddddddkdddddk',
      'kkkkkkkkkkkkkkkk',
      'kddddkdddddddddk',
      'kddddkdddddddddk',
      'kdpddkdddpdddddk',
      'kddddkdddddddddk',
      'kddddkdddppddddk',
      'kddddkdddddddddk',
      'kkkkkkkkkkkkkkkk',
    ],
    wall: [
      'kkkkkkkkkkkkkkkk',
      'khhhhhhhhhhhhhhk',
      'khhhhhhhhhhhhhhk',
      'khhwhhhhhhhhhhhk',
      'khhhhhhhhhhhhhhk',
      'khhhhhhhhhhhhhhk',
      'kkkkkkkkkkkkkkkk',
      'khhhhhhkhhhhhhhk',
      'khhhhhhkhhhhhhhk',
      'khhhhhhkhhhhhhwk',
      'khhhhhhkhhhhhhhk',
      'khhhhhhkhhhhhhhk',
      'kkkkkkkkkkkkkkkk',
      'khhhhhhhhhhhhhhk',
      'khhhhhhhhhhhhhhk',
      'kkkkkkkkkkkkkkkk',
    ],
    fog: [
      'kkkkkkkkkkkkkkkk',
      'kkkkdkkkkkkkkdkk',
      'kkkdkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkdk',
      'kkkkdkkkkkkkkkkk',
      'kkkkkkkkkkkkdkkk',
      'kkkdkkkkkkkkkkkk',
      'kkkkkkkkdkkkkkkk',
      'kkkkkkkkkkkdkkkk',
      'kkdkkkkkkkkkkkkk',
      'kkkkkkkkkkkkdkkk',
      'kkkkkkkdkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkdkkkkkkkkddddk',
      'kkkkkkkkkkkkdkkk',
      'kkkkkkkkkkkkkkdk',
    ],
    start: [
      'dddddddddddddddd',
      'dddddddddddddddd',
      'ddddddbbbbdddddd',
      'ddddbbddddbbdddd',
      'dddbddddddddbddd',
      'ddbddddddddddbdd',
      'ddbddddkkddddbdd',
      'ddbdddkkkkdddbdd',
      'ddbdddkkkkdddbdd',
      'ddbddddkkddddbdd',
      'ddbddddddddddbdd',
      'dddbddddddddbddd',
      'ddddbbddddbbdddd',
      'ddddddbbbbdddddd',
      'dddddddddddddddd',
      'dddddddddddddddd',
    ],
    stairs: [
      'kkkkkkkkkkkkkkkk',
      'khhhhhhhhhhhhhhk',
      'kbbbbbbbbbbbbbbk',
      'khhhhhhhhhhhhhhk',
      'khhhhhhhhhhhhhhk',
      'kkkkkkkkkkkkkkkk',
      'khhhhhhhhhhhhhhk',
      'kbbbbbbbbbbbbbbk',
      'khhhhhhhhhhhhhhk',
      'kkkkkkkkkkkkkkkk',
      'kddddddddddddddk',
      'kbbbbbbbbbbbbbbk',
      'kddddddddddddddk',
      'kkkkkkkkkkkkkkkk',
      'kppppppppppppppk',
      'kkkkkkkkkkkkkkkk',
    ],
    exit: [
      'kkkkkkkkkkkkkkkk',
      'khhhhhhhhhhhhhhk',
      'khhhhhhhhhhhhhhk',
      'khhhhkkkkkkhhhhk',
      'khhhkkOOOOkkhhhk',
      'khkOooOooOoookhk',
      'khkoOooooooOokhk',
      'khkooOooooOookhk',
      'khkOoooooOoookhk',
      'khkoooOoooooOkhk',
      'khkOooooooOookhk',
      'khkooOoooOoookhk',
      'khkOooOoooOookhk',
      'khkoooOoooOookhk',
      'khkkkkkkkkkkkkhk',
      'kddddddddddddddk',
    ],
    trap: [
      'dddddddddddddddd',
      'kkkkkkkkkkkkkkkk',
      'kppppppppppppppk',
      'kppbppbppbppbppk',
      'kpbbpbbpbbpbbppk',
      'kpbbpbbpbbpbbppk',
      'kbbbbbbbbbbbbbbk',
      'kppppppppppppppk',
      'kpRRpppppppRRppk',
      'kpRRRpppppRRRppk',
      'kppRRpppppRRpppk',
      'kppppppppppppppk',
      'kppppppppppppppk',
      'kkkkkkkkkkkkkkkk',
      'dddddddddddddddd',
      'dddddddddddddddd',
    ],
    fire: [
      '.......kk.......',
      '......kOOk......',
      '.....kOooOk.....',
      '....kOoOOok.....',
      '...kOoOOOok.....',
      '..kOoOOOOook....',
      '..kOoOOOOOok....',
      '.kOoOOOOOOook...',
      '.kOooOOOOOook...',
      '.kOooOOOOOook...',
      '..kOoooooOok....',
      '..koooooooook...',
      '...kooooooook...',
      '....kooooook....',
      '.....kooook.....',
      '......kkkk......',
    ],
    vial_vida: [
      '......kkkk......',
      '......kbbk......',
      '......kbbk......',
      '.....kbBBbk.....',
      '.....kbBBbk.....',
      '....kbRRRRbk....',
      '...kbRRRRRRbk...',
      '..kbRRRRRRRRbk..',
      '..kbRRrRRrRRbk..',
      '..kbRRRRRRRRbk..',
      '..kbRrRRRRrRbk..',
      '..kbRRRRRRRRbk..',
      '..kbRRRRRRRRbk..',
      '...kbRRRRRRbk...',
      '....kkkkkkkk....',
      '................',
    ],
    vial_frio: [
      '......kkkk......',
      '......kbbk......',
      '......kbbk......',
      '.....kbBBbk.....',
      '.....kbGGbk.....',
      '....kbGGGGbk....',
      '...kbGGGGGGbk...',
      '..kbGGGGGGGGbk..',
      '..kbGGgGGgGGbk..',
      '..kbGGGGGGGGbk..',
      '..kbGgGGGGgGbk..',
      '..kbGGGGGGGGbk..',
      '..kbGGGGGGGGbk..',
      '...kbGGGGGGbk...',
      '....kkkkkkkk....',
      '................',
    ],
    esencia: [
      '......keek......',
      '.....keeeek.....',
      '....keeeeeek....',
      '...keeeeeeeek...',
      '..keeOOOOOOeek..',
      '.keeOOOOOOOOeek.',
      'keeOOOOOOOOOOeek',
      'keeOOOOOOOOOOeek',
      '.keeOOOOOOOOeek.',
      '..keeOOOOOOeek..',
      '...keeeeeeeek...',
      '....keeeeeek....',
      '.....keeeek.....',
      '......keek......',
      '.......kk.......',
      '................',
    ],
    pergamino: [
      '................',
      '..kkkkkkkkkkkk..',
      '..kmmmmmmmmmmk..',
      '..kbBBBBBBBBbk..',
      '..kbBkkkkkkBbk..',
      '..kbBBBBBBBBbk..',
      '..kbBkkkkBBbbk..',
      '..kbBBBBBBBBbk..',
      '..kbBkkkkkkBbk..',
      '..kbBBBBBBBBbk..',
      '..kbBkkkkkkBbk..',
      '..kbBBBBBBBBbk..',
      '..kbbbbbbbbbbk..',
      '..kmmmmmmmmmmk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
    enemy: [
      '................',
      '................',
      '..k..........k..',
      '..kk........kk..',
      '..kkkkkkkkkkkk..',
      '..kbBBBBBBBBbk..',
      '..kbRRbBBbRRbk..',
      '..kbRRbBBbRRbk..',
      '..kbBBBBBBBBbk..',
      '..kbBkkBBkkBbk..',
      '..kbbbbbbbbbbk..',
      '..kbBbBbBbBbBk..',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
      '................',
    ],
    heart: [
      '................',
      '....kk....kk....',
      '....kRk..kRk....',
      '...kRRRkkRRRk...',
      '..kRRRRRRRRRRk..',
      '.kRRrRRRRRRrRRk.',
      '.kRRrRRRRRRrRRk.',
      '.kRRRRRRRRRRRRk.',
      '..kRRRRRRRRRRk..',
      '..kRRRRRRRRRRk..',
      '...kRRRRRRRRk...',
      '....kRRRRRRk....',
      '.....kRRRRk.....',
      '......kRRk......',
      '.......kk.......',
      '................',
    ],
    heat: [
      '................',
      '.......kk.......',
      '......kOOk......',
      '.....kOOOOk.....',
      '....kOOooOOk....',
      '...kOOooooOOk...',
      '...kOooooooOk...',
      '..kOooooooooOk..',
      '..kOoooRRoooOk..',
      '..koooRRRRoook..',
      '..koooRRRRoook..',
      '...kOooRRooOk...',
      '....kOooooOk....',
      '.....kkkkkk.....',
      '................',
      '................',
    ],
    energy: [
      '................',
      '................',
      '..........kkkk..',
      '.........kMMMMk.',
      '........kMMMMk..',
      '.......kMMMMk...',
      '......kMOOMk....',
      '.....kMOOOOMk...',
      '.....kMOOOOMk...',
      '....kMOOOMkk....',
      '....kkMMMMk.....',
      '.....kMMMk......',
      '......kMMk......',
      '......kMk.......',
      '.......kk.......',
      '................',
    ],
    clock: [
      '................',
      '.....kkkkkk.....',
      '...kkmMMMMmkk...',
      '..kmmbbbbbbmmk..',
      '.kmbbbbbbbbbbmk.',
      '.kmbbbbkbbbbbmk.',
      '.kmbbbbkbbbbbmk.',
      '.kmbbbbkbbbbbmk.',
      '.kmbbbbkkkkkbmk.',
      '.kmbbbbbbbbbbmk.',
      '.kmbbbbbbbbbbmk.',
      '.kmbbbbbbbbbbmk.',
      '..kmmbbbbbbmmk..',
      '...kkmMMMMmkk...',
      '.....kkkkkk.....',
      '................',
    ],
    skull: [
      '................',
      '....kkkkkkkk....',
      '..kkbbbbbbbbkk..',
      '..kbbBBBBBBbbk..',
      '.kbbBBBBBBBBbbk.',
      '.kbBkkkBBkkkBbk.',
      '.kbBkkkBBkkkBbk.',
      '.kbBBBBBBBBBBbk.',
      '.kbbBBBkkBBBbbk.',
      '.kbbbBBBBBBbbbk.',
      '..kbbbbbbbbbbk..',
      '..kbBbBbBbBbbk..',
      '...kbBbBbBbBk...',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    stump: [
      '................',
      '.....kkkkkk.....',
      '....kbbbbbbk....',
      '....kbBBBbbk....',
      '....kbbkkbbk....',
      '....kbBBBbbk....',
      '....kbbkkbbk....',
      '....kbBBBbbk....',
      '....kbbbbbbk....',
      '....kkkkkkkk....',
      '....krRRRRrk....',
      '....krRRRRrk....',
      '.....krrrrk.....',
      '......kkkk......',
      '................',
      '................',
    ],
    card: [
      '................',
      '..kkkkkkkkkkkk..',
      '..kpddddddddpk..',
      '..kddddddddddk..',
      '..kddddbbddddk..',
      '..kdddbBBbdddk..',
      '..kdddbBBbdddk..',
      '..kdddbbbbdddk..',
      '..kddddbbddddk..',
      '..kddddbbddddk..',
      '..kddddbbddddk..',
      '..kddddddddddk..',
      '..kppddddddppk..',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
    ],
    table: [
      '................',
      '..kkkkkkkkkkkk..',
      '..kbbbbbbbbbbk..',
      '..kbBBBBBBBBbk..',
      '..kbBkkkkkkBbk..',
      '..kbBBBBBBBBbk..',
      '..kbBkkkkkkBbk..',
      '..kbBBBBBBBBbk..',
      '..kbbbbbbbbbbk..',
      '..kkkkkkkkkkkk..',
      '...khhk..khhk...',
      '...khhk..khhk...',
      '...khhk..khhk...',
      '..kkhhkkkkhhkk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },

  /** Limb pieces: 28 keys, each drawn at its natural size (head 12x12, torso 14x16, arm 6x14, leg 6x12). */
  _PIECES: {
    head_skull: [
      '....bbbb....',
      '..bbBBBBbb..',
      '.bBBBBBBBBb.',
      '.bBkkBBkkBb.',
      '.bBkkBBkkBb.',
      '.bBBBBBBBBb.',
      '.bBBbbbbBBb.',
      '..bBBBBBBb..',
      '..bBkbkbkB..',
      '...bBbBbB...',
      '...bbbbbb...',
      '....kkkk....',
    ],
    head_crow: [
      '............',
      '.....kkkk...',
      '...kkddddk..',
      '..kdddddddk.',
      '..kddRdddddk',
      '..kdddddddkk',
      '..kdddddddk.',
      '..kddddddk..',
      '...kddddk...',
      '....kddk....',
      '....kddk....',
      '.....kk.....',
    ],
    head_jar: [
      '...kkkkkk...',
      '..kMMMMMMk..',
      '..kwwwwwwk..',
      '.kwGwwwwGwk.',
      '.kwbsssbwwk.',
      '.kwsrsrsswk.',
      '.kwbssssbwk.',
      '.kwbbbbbbwk.',
      '.kwGwwwwGwk.',
      '..kwwwwwwk..',
      '..kMMMMMMk..',
      '...kkkkkk...',
    ],
    head_helm: [
      '..kkkkkkkk..',
      '.khhhhhhhhk.',
      '.khwwwwwwhk.',
      '.khhhhhhhhk.',
      '.khkkkkkkhk.',
      '.khMMMMMMhk.',
      '.khhhhhhhhk.',
      '.khkkkkkkhk.',
      '.khhhhhhhhk.',
      '..khhhhhhk..',
      '..kmmmmmmk..',
      '...kkkkkk...',
    ],
    head_hound: [
      '.kk......kk.',
      '.kdk....kdk.',
      '.kddkkkkddk.',
      '.kddssssddk.',
      '.kdsSSssdddk',
      '.kddssssdddk',
      '.kbddddddbk.',
      '.kkssssssk..',
      '..kRRRRkk...',
      '..kbkbkbk...',
      '...kkkkk....',
      '...kssssk...',
    ],
    head_scholar: [
      '..kkkkkkkk..',
      '.kppppppppk.',
      '.kppppppppk.',
      '.kpddddddpk.',
      '.kpdOOdddpk.',
      '.kpdOOdddpk.',
      '.kpddddddpk.',
      '.kppddddppk.',
      '..kpppppppk.',
      '..kppppppk..',
      '...kppppk...',
      '....kkkk....',
    ],
    head_rat: [
      '..kkkk......',
      '.kssssk.....',
      '.ksSsskk....',
      '.kssssskkk..',
      '.kssssssssk.',
      '.ksssssssssk',
      '.ksssssssskk',
      '.kkssssskk..',
      '..kssssk....',
      '..kRRRkk....',
      '...kkk......',
      '...kssk.....',
    ],

    torso_stitch: [
      '...kkkkkkkk...',
      '..kkssssssskk.',
      '.kkssssssssskk',
      '.ksssssssssssk',
      '.kSssssssssssk',
      '.ksssssbsssssk',
      '.kssssBkBssssk',
      '.ksssssbsssssk',
      '.ksssssbsssssk',
      '.kssssBkBssssk',
      '.ksssssbsssssk',
      '.ksssssssssssk',
      '..ksssssssssk.',
      '..kSsssssssk..',
      '..kssssssssk..',
      '...kkkkkkkk...',
    ],
    torso_brass: [
      '...kssssssk...',
      '..kkmmmmmmkk..',
      '.kkmMMMMMMmkk.',
      '.kmMMMMMMMMmk.',
      '.kmwMMMMMMwmk.',
      '.kmMMMMMMMMmk.',
      '.kmMMMMMMMMmk.',
      '.kmwMMMMMMwmk.',
      '.kmMMMMMMMMmk.',
      '.kmMMMMMMMMmk.',
      '.kmwMMMMMMwmk.',
      '.kmMMMMMMMMmk.',
      '..kmMMMMMMmk..',
      '..kmmMMMMmmk..',
      '..kkmmmmmmkk..',
      '...kssssssk...',
    ],
    torso_barrel: [
      '...kssssssk...',
      '..kkhhhhhhkk..',
      '.kbbbbbbbbbbk.',
      '.kbBBBBBBBBbk.',
      '.kbbbbbbbbbbk.',
      '.kwwwwwwwwwwk.',
      '.kbbbbbbbbbbk.',
      '.kbBBBBBBBBbk.',
      '.kbbbbbbbbbbk.',
      '.kwwwwwwwwwwk.',
      '.kbbbbbbbbbbk.',
      '.kbBBBBBBBBbk.',
      '.kbbbbbbbbbbk.',
      '..kbbbbbbbbk..',
      '..kkhhhhhhkk..',
      '...kssssssk...',
    ],
    torso_ribcage: [
      '...kssssssk...',
      '..kksssssskk..',
      '.kSssbbbbssSk.',
      '.kbssssssssbk.',
      '.kbbssssssbbk.',
      '.kbssssssssbk.',
      '.kbbssssssbbk.',
      '.kbssssssssbk.',
      '.kbbssssssbbk.',
      '.kbssssssssbk.',
      '.kbbssssssbbk.',
      '.kbssssssssbk.',
      '.kssbbbbbbssk.',
      '..kssssssssk..',
      '..kssssssssk..',
      '...kssssssk...',
    ],
    torso_robe: [
      '...kssssssk...',
      '..kppppppppk..',
      '.kpppddddpppk.',
      '.kppddddddppk.',
      '.kpppddddpppk.',
      '.kppppdpppppk.',
      '.kpppppppppppk',
      '.kppppppppppk.',
      '.kmMMMMMMMMmk.',
      '.kppppppppppk.',
      '.kppppdpppppk.',
      '.kppppppppppk.',
      '.kppppdpdpppk.',
      '.kppppppppppk.',
      '..kppppppppk..',
      '...kssssssk...',
    ],
    torso_fur: [
      '...kssssssk...',
      '..kSssssssSk..',
      '.ksSSssssSSsk.',
      '.kssssssssssk.',
      '.kSssssssssSk.',
      '.ksssddddsssk.',
      '.ksssddddsssk.',
      '.kSssddddssSk.',
      '.ksssddddsssk.',
      '.ksssddddsssk.',
      '.ksssddddsssk.',
      '.kSssssssssSk.',
      '.kssssssssssk.',
      '.kssssssssssk.',
      '..kSssssssSk..',
      '...kssssssk...',
    ],

    arm_bone: [
      '.kkkk.',
      '.kssk.',
      '.kssk.',
      '.kbbk.',
      '.kbbk.',
      '.kkkk.',
      '.kbbk.',
      '.kbbk.',
      '.kbbk.',
      '.kkkk.',
      '.kbbk.',
      'kbbbbk',
      'kbkbkk',
      '.k..k.',
    ],
    arm_claw: [
      '.kkkk.',
      '.kssk.',
      '.kSsk.',
      '.kssk.',
      '.kssk.',
      '.kkkk.',
      '.kssk.',
      '.kssk.',
      '.kssk.',
      '.kssk.',
      '.kbbk.',
      'kbbbbk',
      'kbkbkk',
      '.R..R.',
    ],
    arm_saw: [
      '.kkkk.',
      '.kssk.',
      '.kSsk.',
      '.kkkk.',
      '.khhk.',
      'bkhwk.',
      '.khwk.',
      'bkhhk.',
      '.khwk.',
      'bkhwk.',
      '.khhk.',
      'bkhwk.',
      '.khhk.',
      '.kkkk.',
    ],
    arm_tentacle: [
      '.kkkk.',
      '.kssk.',
      '.kssk.',
      '.kSsk.',
      '.kssk.',
      '.kppk.',
      '.kssk.',
      '.kssk.',
      '.kppk.',
      '.kssk.',
      '.kssk.',
      '.kppk.',
      '..kkk.',
      '...kk.',
    ],
    arm_brass: [
      '.kkkk.',
      '.kssk.',
      '.kkkk.',
      '.kmmk.',
      '.kMMk.',
      '.kmmk.',
      '.kwwk.',
      '.kwwk.',
      '.kmmk.',
      '.kMMk.',
      '.kmmk.',
      'kmmmmk',
      'kMbMbk',
      '.kkkk.',
    ],
    arm_needle: [
      '.kkkk.',
      '.kssk.',
      '.kSsk.',
      '.kssk.',
      '.kkkk.',
      '.kmwk.',
      '.kmwk.',
      '.kmwk.',
      '.kwwk.',
      '.kwwk.',
      '..kk..',
      '..wk..',
      '..wk..',
      '..bk..',
    ],
    arm_scholar: [
      '.kkkk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kmmk.',
      'kssssk',
      'kbkbkk',
      '.k..k.',
    ],
    arm_paw: [
      '.kkkk.',
      '.kssk.',
      '.ksSk.',
      '.kssk.',
      '.kSSk.',
      '.kssk.',
      '.kSSk.',
      '.kssk.',
      '.ksSk.',
      '.kssk.',
      '.kssk.',
      'kssssk',
      'ksbsbk',
      '.b..b.',
    ],

    leg_bone: [
      '.kkkk.',
      '.kssk.',
      '.kbbk.',
      '.kbbk.',
      '.kbbk.',
      '.kkkk.',
      '.kbbk.',
      '.kbbk.',
      '.kbbk.',
      '.kkkk.',
      'kbbbbk',
      'kkbbkk',
    ],
    leg_hoof: [
      '.kkkk.',
      '.kssk.',
      '.kssk.',
      '.ksSk.',
      '.kssk.',
      '.kppk.',
      '.kddk.',
      '.kddk.',
      '.kddk.',
      '.kppk.',
      'kddddk',
      'kkddkk',
    ],
    leg_spring: [
      '.kssk.',
      '.kmmk.',
      '.kwwk.',
      '.kmmk.',
      '.kwwk.',
      '.kmmk.',
      '.kwwk.',
      '.kmmk.',
      '.kwwk.',
      '.kmmk.',
      'kmmmmk',
      '.kkkk.',
    ],
    leg_wheel: [
      '.kkkk.',
      '.kssk.',
      '.kssk.',
      '.kkkk.',
      'kmmmmk',
      'kmwwmk',
      'kwGGwk',
      'kmwwmk',
      'kmwwmk',
      'kmmmmk',
      '.kkkk.',
      '......',
    ],
    leg_hound: [
      '.kkkk.',
      '.kssk.',
      '.kSsk.',
      '.kssk.',
      '.kssk.',
      '.kkkk.',
      '.kssk.',
      '.kssk.',
      '.kssk.',
      '.kssk.',
      'ksssk.',
      'kbkbkk',
    ],
    leg_scholar: [
      '.kkkk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kppk.',
      '.kssk.',
      '.kssk.',
      '.kkkk.',
      'kddddk',
      'kkddkk',
    ],
    leg_rat: [
      '.kkkk.',
      '.kssk.',
      '.kssk.',
      '.kSsk.',
      '.kssk.',
      '.kssk.',
      '.kssk.',
      '.kssk.',
      '.kssk.',
      '.kssk.',
      '.kssk.',
      'kbkbk.',
    ],
  },

  /** Bandaged stumps, drawn in place of a null slot; same sizes as the pieces of their type. */
  _STUBS: {
    head: [
      '..krrk..',
      '.kbbbbk.',
      '.kbkkbk.',
      '.kbbbbk.',
      '.kbbbbk.',
      '..kkkk..',
    ],
    torso: [
      '..krrrrrrrrk..',
      '.kbBBBBBBBBbk.',
      '.kbbkkkkkkbbk.',
      '.kbBBBBBBBBbk.',
      '.kbbkkkkkkbbk.',
      '.kbBBBBBBBBbk.',
      '.kbbkkkkkkbbk.',
      '.kbBBBBBBBBbk.',
      '.kbbkkkkkkbbk.',
      '.kbBBBBBBBBbk.',
      '.kbbkkkkkkbbk.',
      '.kbBBBBBBBBbk.',
      '.kbbkkkkkkbbk.',
      '.kbBBBBBBBBbk.',
      '.kbbkkkkkkbbk.',
      '..kkkkkkkkkk..',
    ],
    arm: [
      '.kkkk.',
      '.kbbk.',
      '.kbBk.',
      '.kbbk.',
      '.kbBk.',
      '.kbbk.',
      '.krrk.',
      '..kk..',
    ],
    leg: [
      'kkkkkk',
      'kbBBbk',
      'kbbbbk',
      'kbBBbk',
      'kbbbbk',
      'kbbbbk',
      'krrrrk',
      '.kkkk.',
    ],
  },
};
