/* Deadlock Deck — language layer. Loaded before every other file, because the
 * data files call DD.t() while they build their tables.
 *
 * Spanish is the source language: the key of every entry below is the exact
 * Spanish literal as it is written in the code, and a string that is not a key
 * passes through untouched. Strings that carry numbers are split in the call
 * site so only the fixed part reaches the dictionary. */
(function () {
  'use strict';

  var DD = window.DD = window.DD || {};

  var EN = {
    /* ---------------------------------------------- vocabulary (core/ns.js) */
    'Cabeza': 'Head',
    'Brazo Izq.': 'Left Arm',
    'Brazo Der.': 'Right Arm',
    'Pierna Izq.': 'Left Leg',
    'Pierna Der.': 'Right Leg',

    /* ------------------------------------------------ card names (data/cards.js) */
    'Puñetazo de Muñón': 'Stump Punch',
    'Guardia de Muñón': 'Stump Guard',
    'Forcejeo': 'Scrabble',
    'Tambaleo': 'Lurch',
    'Chillido': 'Screech',
    'Mordisco': 'Bite',
    'Mirada Osaria': 'Ossuary Glare',
    'Golpe de Cráneo': 'Skull Tap',
    'Foco Óseo': 'Bone Focus',
    'Escupitajo Sangriento': 'Blood Spit',
    'Alarido Crudo': 'Raw Scream',
    'Engullir': 'Gorge',
    'Válvula de Presión': 'Pressure Valve',
    'Disparo de Engranaje': 'Cog Shot',
    'Guardia de Latón': 'Brass Guard',
    'Sobremarcha': 'Overclock',
    'Intuición Ectoplásmica': 'Ectoplasmic Insight',
    'Sifón de Almas': 'Soul Siphon',
    'Mirada de Pavor': 'Dread Gaze',
    'Tercer Ojo': 'Third Eye',
    'Goteo Venenoso': 'Venom Drip',
    'Destilar': 'Distill',
    'Vapores Debilitantes': 'Weakening Fumes',
    'Veneno Mental': 'Mind Venom',
    'Cero Absoluto': 'Absolute Zero',
    'Permafrost': 'Permafrost',
    'Pensamiento Gélido': 'Frozen Thought',
    'Mirada Entumecedora': 'Numbing Stare',
    'Astilla Costal': 'Rib Splinter',
    'Placa Ósea': 'Bone Plate',
    'Guardia Quebradiza': 'Brittle Guard',
    'Ligadura de Cartílago': 'Cartilage Ligature',
    'Sangría': 'Bloodletting',
    'Festín Carmesí': 'Crimson Feast',
    'Remiendo Visceral': 'Visceral Patch',
    'Muro de Remaches': 'Rivet Wall',
    'Purga de Caldera': 'Boiler Purge',
    'Sobrepresión': 'Overpressure',
    'Batería de Almas': 'Soul Battery',
    'Velo de Ectoplasma': 'Ectoplasm Veil',
    'Lamento': 'Wail',
    'Comunión Espectral': 'Spectral Communion',
    'Estallido de Bilis': 'Bile Burst',
    'Sangrado de Residuo': 'Residue Bleed',
    'Armadura Cáustica': 'Caustic Armour',
    'Frasco de Purga': 'Purge Flask',
    'Muro Glaciar': 'Glacier Wall',
    'Corazón de Hielo': 'Heart of Ice',
    'Sumidero Térmico': 'Heat Sink',
    'Armadura de Escarcha': 'Frost Armour',
    'Zarpazo': 'Claw Swipe',
    'Espina Ósea': 'Bone Spur',
    'Furia de Muñones': 'Stump Fury',
    'Desgarrar': 'Rend',
    'Ofrenda de Sangre': 'Blood Offering',
    'Festín de Carne': 'Flesh Feast',
    'Puñetazo de Pistón': 'Piston Punch',
    'Ariete Hidráulico': 'Hydraulic Ram',
    'Ventilación Hirviente': 'Scalding Vent',
    'Toque Fantasmal': 'Ghostly Touch',
    'Rayo Espectral': 'Spectral Bolt',
    'Sanguijuela Etérea': 'Ethereal Leech',
    'Aguijonazo': 'Sting',
    'Látigo Tóxico': 'Toxic Lash',
    'Estallido Venenoso': 'Venom Burst',
    'Suero de Ruina': 'Serum of Ruin',
    'Estocada de Lanza': 'Spear Thrust',
    'Púa Gélida': 'Frozen Spike',
    'Congelación': 'Deep Freeze',
    'Lanza Criogénica': 'Cryogenic Lance',
    'Garfio Arrastrador': 'Dragging Hook',
    'Tirón de Cadena': 'Chain Pull',
    'Garfio Carnicero': 'Meat Hook',
    'Doncella de Hierro': 'Iron Maiden',
    'Guadaña de Hueso': 'Bone Scythe',
    'Rociada de Médula': 'Marrow Spray',
    'Tañido del Segador': 'Toll of the Reaper',
    'Osario Ascendente': 'Rising Ossuary',
    'Paso de Zancos': 'Stilt Step',
    'Marcha de Hueso': 'Bone March',
    'Lanzamiento de Fémur': 'Femur Throw',
    'Marcha de Nudillos': 'Knuckle Walk',
    'Carrera Sanguínea': 'Blood Run',
    'Latigazo de Tendón': 'Tendon Lash',
    'Maratón de Sangre': 'Blood Marathon',
    'Salto de Muelle': 'Spring Leap',
    'Patada Neumática': 'Pneumatic Kick',
    'Escape de Vapor': 'Steam Escape',
    'Paso Etéreo': 'Ethereal Step',
    'Correría Espectral': 'Spectral Dash',
    'Desborde Etéreo': 'Ethereal Overflow',
    'Zancada del Vacío': 'Void Stride',
    'Rastro Ácido': 'Acid Trail',
    'Paso Corrosivo': 'Corrosive Step',
    'Zancada de Alambique': 'Alembic Stride',
    'Vertido Tóxico': 'Toxic Spill',
    'Pisada de Permafrost': 'Permafrost Tread',
    'Pisotón de Granizo': 'Hailstone Stomp',
    'Invierno Eterno': 'Eternal Winter',
    'Marcha Helada': 'Frozen March',

    /* ---------------------------------------- card descriptions (data/cards.js) */
    'Inflige 3 de daño.': 'Deal 3 damage.',
    'Ganas 3 de Bloqueo.': 'Gain 3 Block.',
    'Ganas 2 de residuo y enfrías 4 de calor.': 'Gain 2 residue and cool 4 heat.',
    'Inflige 5 de daño y ganas 3 de Bloqueo.': 'Deal 5 damage and gain 3 Block.',
    'Aplica 1 de Debilidad y 1 de Vulnerabilidad a todos los enemigos.': 'Apply 1 Weak and 1 Vulnerable to all enemies.',
    'Inflige 6 de daño y aplica 1 de Sangrado.': 'Deal 6 damage and apply 1 Bleed.',
    'Aplica 1 de Debilidad.': 'Apply 1 Weak.',
    'Inflige 6 de daño.': 'Deal 6 damage.',
    'Robas 2 cartas.': 'Draw 2 cards.',
    'Inflige 3 de daño y aplica 1 de Sangrado.': 'Deal 3 damage and apply 1 Bleed.',
    'Aplica 2 de Debilidad a todos los enemigos.': 'Apply 2 Weak to all enemies.',
    'Inflige 5 de daño. Te curas 4 PV.': 'Deal 5 damage. Heal 4 HP.',
    'Enfrías 6 de calor de este socket.': 'Cool 6 heat on this socket.',
    'Inflige 7 de daño.': 'Deal 7 damage.',
    'Ganas 8 de Bloqueo.': 'Gain 8 Block.',
    'Ganas 2 de energía. Esta carta se agota.': 'Gain 2 energy. This card exhausts.',
    'Inflige 5 de daño. Te curas 5 PV.': 'Deal 5 damage. Heal 5 HP.',
    'Aplica 2 de Vulnerabilidad a todos los enemigos y aturde 1 turno al objetivo.': 'Apply 2 Vulnerable to all enemies and stun the target for 1 turn.',
    'Robas 3 cartas y ganas 1 de energía.': 'Draw 3 cards and gain 1 energy.',
    'Inflige 4 de daño y aplica 3 de Veneno.': 'Deal 4 damage and apply 3 Poison.',
    'Ganas 4 de residuo.': 'Gain 4 residue.',
    'Aplica 2 de Debilidad y 2 de Vulnerabilidad a todos los enemigos.': 'Apply 2 Weak and 2 Vulnerable to all enemies.',
    'Aplica 8 de Veneno a todos los enemigos.': 'Apply 8 Poison to all enemies.',
    'Aplica 3 de Vulnerabilidad y 2 de Debilidad a todos los enemigos. Enfrías 18 de calor.': 'Apply 3 Vulnerable and 2 Weak to all enemies. Cool 18 heat.',
    'Ganas 12 de Bloqueo y enfrías 12 de calor.': 'Gain 12 Block and cool 12 heat.',
    'Robas 2 cartas y enfrías 6 de calor.': 'Draw 2 cards and cool 6 heat.',
    'Inflige 5 de daño y aplica 1 de Debilidad a todos los enemigos.': 'Deal 5 damage and apply 1 Weak to all enemies.',
    'Inflige 4 de daño.': 'Deal 4 damage.',
    'Ganas 7 de Bloqueo.': 'Gain 7 Block.',
    'Quedas Frágil 2 (ganas un 25% menos de Bloqueo). Ganas 14 de Bloqueo.': 'Become Frail 2 (gain 25% less Block). Gain 14 Block.',
    'Ganas 7 de Bloqueo y te curas 2 PV.': 'Gain 7 Block and heal 2 HP.',
    'Inflige 4 de daño. Pierdes 2 PV.': 'Deal 4 damage. Lose 2 HP.',
    'Inflige 9 de daño. Te curas 6 PV.': 'Deal 9 damage. Heal 6 HP.',
    'Te curas 6 PV.': 'Heal 6 HP.',
    'Ganas 14 de Bloqueo.': 'Gain 14 Block.',
    'Enfrías 8 de calor y ganas 3 de Bloqueo.': 'Cool 8 heat and gain 3 Block.',
    'Ganas 3 de Bloqueo por cada 25 de calor en este socket.': 'Gain 3 Block for every 25 heat on this socket.',
    'Ganas 1 de energía.': 'Gain 1 energy.',
    'Ganas 6 de Bloqueo y robas 1 carta.': 'Gain 6 Block and draw 1 card.',
    'Inflige 6 de daño a todos los enemigos.': 'Deal 6 damage to all enemies.',
    'Te curas 10 PV y robas 2 cartas.': 'Heal 10 HP and draw 2 cards.',
    'Inflige 4 de daño y aplica 2 de Veneno a todos los enemigos.': 'Deal 4 damage and apply 2 Poison to all enemies.',
    'Ganas 5 de residuo. El enemigo soltará un miembro extra.': 'Gain 5 residue. The enemy will drop an extra limb.',
    'Ganas 7 de Bloqueo y aplica 2 de Veneno a todos los enemigos.': 'Gain 7 Block and apply 2 Poison to all enemies.',
    'Te curas 4 PV, ganas 3 de residuo y robas 1 carta.': 'Heal 4 HP, gain 3 residue and draw 1 card.',
    'Ganas 24 de Bloqueo y enfrías 10 de calor.': 'Gain 24 Block and cool 10 heat.',
    'Ganas 8 de Bloqueo, enfrías 8 de calor y restauras 10 de integridad.': 'Gain 8 Block, cool 8 heat and restore 10 integrity.',
    'Ganas 6 de Bloqueo y enfrías 6 de calor.': 'Gain 6 Block and cool 6 heat.',
    'Ganas 8 de Bloqueo y restauras 4 de integridad.': 'Gain 8 Block and restore 4 integrity.',
    'Inflige 4 de daño y aplica 1 de Sangrado.': 'Deal 4 damage and apply 1 Bleed.',
    'Inflige 8 de daño.': 'Deal 8 damage.',
    'Inflige 6 de daño por cada miembro amputado.': 'Deal 6 damage for each severed limb.',
    'Inflige 6 de daño y aplica 2 de Sangrado.': 'Deal 6 damage and apply 2 Bleed.',
    'Pierdes 4 PV. Ganas 2 de energía.': 'Lose 4 HP. Gain 2 energy.',
    'Inflige 8 de daño. Te curas 8 PV.': 'Deal 8 damage. Heal 8 HP.',
    'Inflige 14 de daño.': 'Deal 14 damage.',
    'Inflige 6 de daño y ganas 4 de Bloqueo.': 'Deal 6 damage and gain 4 Block.',
    'Inflige 4 de daño por cada 25 de calor en este socket. Añades 6 de calor.': 'Deal 4 damage for every 25 heat on this socket. Add 6 heat.',
    'Inflige 4 de daño y robas 1 carta.': 'Deal 4 damage and draw 1 card.',
    'Inflige 9 de daño.': 'Deal 9 damage.',
    'Inflige 4 de daño y aplica 4 de Veneno.': 'Deal 4 damage and apply 4 Poison.',
    'Inflige 5 de daño y aplica 3 de Veneno.': 'Deal 5 damage and apply 3 Poison.',
    'Inflige 4 de daño y aplica 1 de Debilidad a todos los enemigos.': 'Deal 4 damage and apply 1 Weak to all enemies.',
    'Inflige 7 de daño y aplica 5 de Veneno a todos los enemigos.': 'Deal 7 damage and apply 5 Poison to all enemies.',
    'Aplica 10 de Veneno y 3 de Vulnerabilidad a todos los enemigos.': 'Apply 10 Poison and 3 Vulnerable to all enemies.',
    'Inflige 3 de daño y enfrías 3 de calor.': 'Deal 3 damage and cool 3 heat.',
    'Inflige 9 de daño y aplica 2 de Debilidad a todos los enemigos.': 'Deal 9 damage and apply 2 Weak to all enemies.',
    'Inflige 14 de daño, aplica 2 de Vulnerabilidad a todos los enemigos y enfrías 8 de calor.': 'Deal 14 damage, apply 2 Vulnerable to all enemies and cool 8 heat.',
    'Inflige 7 de daño y aplica 1 de Debilidad a todos los enemigos.': 'Deal 7 damage and apply 1 Weak to all enemies.',
    'Inflige 6 de daño y robas 1 carta.': 'Deal 6 damage and draw 1 card.',
    'Inflige 8 de daño y aplica 4 de Sangrado a todos los enemigos.': 'Deal 8 damage and apply 4 Bleed to all enemies.',
    'Ganas 5 de Bloqueo por cada 25 de calor en este socket.': 'Gain 5 Block for every 25 heat on this socket.',
    'Inflige 13 de daño.': 'Deal 13 damage.',
    'Inflige 4 de daño y aplica 2 de Sangrado a todos los enemigos.': 'Deal 4 damage and apply 2 Bleed to all enemies.',
    'Inflige 12 de daño y aplica 4 de Sangrado a todos los enemigos.': 'Deal 12 damage and apply 4 Bleed to all enemies.',
    'Inflige 12 de daño por cada miembro amputado y ganas 6 de residuo.': 'Deal 12 damage for each severed limb and gain 6 residue.',
    'Ganas 4 de Bloqueo y enfrías 3 de calor.': 'Gain 4 Block and cool 3 heat.',
    'Inflige 6 de daño y ganas 3 de Bloqueo.': 'Deal 6 damage and gain 3 Block.',
    'Robas 2 cartas. Pierdes 3 PV.': 'Draw 2 cards. Lose 3 HP.',
    'Ganas 1 de energía. Pierdes 2 PV.': 'Gain 1 energy. Lose 2 HP.',
    'Inflige 7 de daño. Te curas 3 PV.': 'Deal 7 damage. Heal 3 HP.',
    'Te curas 8 PV y robas 1 carta.': 'Heal 8 HP and draw 1 card.',
    'Ganas 5 de Bloqueo.': 'Gain 5 Block.',
    'Enfrías 8 de calor.': 'Cool 8 heat.',
    'Robas 1 carta y ganas 3 de Bloqueo.': 'Draw 1 card and gain 3 Block.',
    'Inflige 7 de daño y robas 1 carta.': 'Deal 7 damage and draw 1 card.',
    'Ganas 2 de energía, robas 1 carta y descartas 1 carta al azar.': 'Gain 2 energy, draw 1 card and discard 1 card at random.',
    'Robas 3 cartas y enfrías 8 de calor.': 'Draw 3 cards and cool 8 heat.',
    'Inflige 6 de daño y aplica 1 de Vulnerabilidad a todos los enemigos.': 'Deal 6 damage and apply 1 Vulnerable to all enemies.',
    'Ganas 8 de residuo y enfrías 4 de calor.': 'Gain 8 residue and cool 4 heat.',
    'Aplica 6 de Veneno y 2 de Debilidad a todos los enemigos.': 'Apply 6 Poison and 2 Weak to all enemies.',
    'Ganas 7 de Bloqueo y enfrías 5 de calor.': 'Gain 7 Block and cool 5 heat.',
    'Inflige 8 de daño y aplica 1 de Debilidad a todos los enemigos.': 'Deal 8 damage and apply 1 Weak to all enemies.',
    'Enfrías 30 de calor, restauras 12 de integridad y ganas 8 de Bloqueo.': 'Cool 30 heat, restore 12 integrity and gain 8 Block.',
    'Ganas 1 de energía y enfrías 6 de calor.': 'Gain 1 energy and cool 6 heat.',

    /* ------------------------------------------------------- limbs (data/limbs.js) */
    'Cráneo Osario': 'Ossuary Skull',
    'Un cráneo limpio y hueco, más útil como herramienta que como cabeza.': 'A clean, hollow skull, more useful as a tool than as a head.',
    'Rostro Palpitante': 'Throbbing Face',
    'Una cara prestada que supura y nunca deja de sonreír.': 'A borrowed face that weeps and never stops smiling.',
    'Cráneo de Válvulas': 'Valve Skull',
    'Latón, manómetros y un ojo de cristal que gira solo.': 'Brass, pressure gauges and a glass eye that turns by itself.',
    'Cráneo Vidente': 'Seer Skull',
    'Mira hacia dentro y encuentra cosas que todavía no han ocurrido.': 'It looks inward and finds things that have not happened yet.',
    'Córtex Alquímico': 'Alchemical Cortex',
    'Un cerebro conservado en veneno: sólo piensa en dosis y antídotos.': 'A brain pickled in poison: it thinks only in doses and antidotes.',
    'Mente Criogénica': 'Cryogenic Mind',
    'Piensa despacio, congelando cada idea antes de llegar a usarla.': 'It thinks slowly, freezing every idea before it gets to use it.',
    'Caja Torácica': 'Ribcage',
    'Costillas secas que crujen con cada respiración y aguantan de milagro.': 'Dry ribs that creak with every breath and hold by a miracle.',
    'Torso Palpitante': 'Throbbing Torso',
    'Un tronco de músculo cosido a un corazón que no era suyo.': 'A trunk of muscle sewn to a heart that was not its own.',
    'Coraza de Caldera': 'Boiler Cuirass',
    'Cincuenta remaches y una caldera que nunca acaba de enfriarse.': 'Fifty rivets and a boiler that never quite cools down.',
    'Torso Hueco': 'Hollow Torso',
    'No hay órganos: sólo un hueco que zumba y escupe chispas.': 'No organs: only a hollow that hums and spits sparks.',
    'Saco Venenoso': 'Venom Sac',
    'Un buche traslúcido donde fermentan residuos y promesas.': 'A translucent crop where residue and promises ferment.',
    'Coraza Glacial': 'Glacial Cuirass',
    'Placas de hielo eterno; debajo, algo sigue latiendo muy despacio.': 'Plates of eternal ice; underneath, something is still beating very slowly.',
    'Garra Ósea': 'Bone Claw',
    'Falanges afiladas que se parten al primer golpe mal dado.': 'Sharpened phalanges that snap on the first badly aimed blow.',
    'Brazo de Carne': 'Flesh Arm',
    'Músculo crudo cosido al hombro con hilo de tripa.': 'Raw muscle sewn to the shoulder with gut thread.',
    'Brazo de Pistón': 'Piston Arm',
    'Lento, pesado, y capaz de abollar una puerta de hierro.': 'Slow, heavy, and able to dent an iron door.',
    'Brazo Fantasmal': 'Ghost Arm',
    'Atraviesa la materia, pero el calor lo disuelve como niebla.': 'It passes through matter, but heat dissolves it like fog.',
    'Aguijón Venenoso': 'Venom Stinger',
    'Un aguijón hueco que se rellena solo mientras alguien sangre.': 'A hollow stinger that refills itself as long as someone is bleeding.',
    'Brazo de Garfio': 'Hook Arm',
    'Un garfio de matadero con cadena, polea y muy malos modales.': 'A slaughterhouse hook with chain, pulley and very bad manners.',
    'Lanza de Escarcha': 'Frost Lance',
    'Un brazo convertido en carámbano; el primer golpe es siempre el más frío.': 'An arm turned into an icicle; the first blow is always the coldest.',
    'Brazo Segador': 'Reaper Arm',
    'Cosecha brazos ajenos para alargar el suyo: cada muñón lo hace más fuerte.': 'It harvests other arms to lengthen its own: every stump makes it stronger.',
    'Zancos Óseos': 'Bone Stilts',
    'Dos fémures alargados con bisagras de alambre y mucha prisa.': 'Two femurs stretched out with wire hinges and a lot of hurry.',
    'Piernas de Tendón': 'Tendon Legs',
    'Tendones tensados como cuerdas de violín que se reajustan solos.': 'Tendons strung like violin strings that retune themselves.',
    'Piernas de Muelle': 'Spring Legs',
    'Muelles de coche y tubos de escape por donde resopla todo el cuerpo.': 'Car springs and exhaust pipes the whole body snorts through.',
    'Piernas Espectrales': 'Spectral Legs',
    'No tocan el suelo: flotan un dedo por encima del polvo.': 'They never touch the floor: they hover a finger above the dust.',
    'Piernas Ácidas': 'Acid Legs',
    'Cada paso deja un charco que silba y disuelve la piedra.': 'Every step leaves a puddle that hisses and dissolves the stone.',
    'Pisadas de Escarcha': 'Frost Treads',
    'El suelo se hiela donde pisa; el tiempo también, un poco.': 'The floor freezes where it treads; so does time, a little.',

    /* --------------------------------------------------- enemies (data/enemies.js) */
    'Reptador de Conductos': 'Duct Crawler',
    'Muerde los dedos': 'Bites the fingers',
    'Se enrosca': 'Coils up',
    'Araña los tobillos': 'Claws the ankles',
    'Corre entre los tubos con dedos que no son suyos.': 'It runs through the pipes on fingers that are not its own.',
    'Sanguijuela de Sala': 'Ward Leech',
    'Se adhiere': 'Latches on',
    'Absorbe la sangre': 'Drinks the blood',
    'Suelta las ventosas': 'Releases its suckers',
    'Criada en un frasco, del tamaño de un perro y siempre hambrienta.': 'Raised in a jar, the size of a dog and always hungry.',
    'Homúnculo': 'Homunculus',
    'Manotea sin mirar': 'Flails without looking',
    'Se acurruca': 'Curls up',
    'Chilla hasta aturdir': 'Shrieks until you reel',
    'Un intento fallido que sigue respirando en su frasco roto.': 'A failed attempt that keeps breathing in its broken jar.',
    'Cosetendones': 'Tendonstitcher',
    'Alza el costurón': 'Raises the seam',
    'Ensarta con la aguja': 'Skewers with the needle',
    'Cose los tendones': 'Stitches the tendons',
    'Tira de la sutura': 'Pulls the suture',
    'Cose carne ajena con hilo de plomo y no distingue dueños.': 'It sews borrowed flesh with lead thread and cannot tell owners apart.',
    'Enfermera de la Sala Tres': 'Nurse of Ward Three',
    'Punza con la jeringuilla': 'Jabs with the syringe',
    'Inyecta un calmante': 'Injects a sedative',
    'Marca la carne del rebaño': 'Brands the flesh of the herd',
    'Lanceta al paciente': 'Lancets the patient',
    'Nadie la contrató. Nadie se atreve a despedirla.': 'Nobody hired her. Nobody dares to fire her.',
    'Bruto de Carga': 'Load Brute',
    'Aplasta con el puño': 'Smashes with its fist',
    'Barre con el yugo': 'Sweeps with the yoke',
    'Estrella contra el suelo': 'Slams you into the floor',
    'Arranca de cuajo': 'Tears clean off',
    'Músculo mal cosido. Solo sabe derribar puertas y personas.': 'Badly sewn muscle. All it knows is knocking down doors and people.',
    'Sabueso del Doctor': 'Doctor Hound',
    'Muerde la pantorrilla': 'Bites the calf',
    'Zarpa el costado': 'Claws the flank',
    'Se agazapa': 'Crouches',
    'Demasiadas mandíbulas para un solo perro.': 'Too many jaws for a single dog.',
    'Viuda del Doctor': 'Doctor Widow',
    'Marca la presa': 'Marks the prey',
    'Clava los colmillos': 'Sinks its fangs',
    'Teje la tela': 'Weaves the web',
    'Suelta las larvas': 'Releases the larvae',
    'Se quedó a medio hacer y siguió tejiendo sola.': 'She was left half finished and went on weaving alone.',
    'Alquimista Corrupto': 'Corrupt Alchemist',
    'Escupe bilis verdosa': 'Spits greenish bile',
    'Lanza el matraz': 'Hurls the flask',
    'Derrama el frasco': 'Spills the vial',
    'Remueve la mezcla': 'Stirs the mixture',
    'Anota cada síntoma antes de provocarlo.': 'He writes down every symptom before causing it.',
    'Resucitado': 'Revenant',
    'Desgarra la mortaja': 'Tears the shroud',
    'Se envuelve en el sudario': 'Wraps itself in the winding sheet',
    'Abre la herida vieja': 'Opens the old wound',
    'Vuelve del frío': 'Comes back from the cold',
    'Ya murió una vez y no le pareció motivo para parar.': 'It died once already and did not see that as a reason to stop.',
    'Gólem de Losa': 'Slab Golem',
    'Cierra los pórticos': 'Seals the gateways',
    'Machaca el suelo': 'Pounds the floor',
    'Recompone la losa': 'Reassembles the slab',
    'Sacude la bóveda': 'Shakes the vault',
    'Piedra, plomo y un contrato que nadie leyó hasta el final.': 'Stone, lead and a contract nobody read to the end.',
    'El Cosechador': 'The Harvester',
    'Siega las piernas': 'Reaps the legs',
    'Marca el lote': 'Marks the lot',
    'Cosecha lo sembrado': 'Harvests what was sown',
    'El capataz de la torre. Recoge lo que los demás dejan a medias.': 'The foreman of the tower. He collects what the others leave half done.',

    /* ------------------------------------------------------- traps (data/traps.js) */
    'Pinchos Oxidados': 'Rusted Spikes',
    'Tela de araña, mierda y tétanos. Sobre todo tétanos.': 'Cobwebs, filth and tetanus. Mostly tetanus.',
    'Pinchos de Osario': 'Ossuary Spikes',
    'Fémures afilados hacia arriba. Alguien los colocó a propósito.': 'Femurs sharpened and pointed up. Someone set them there on purpose.',
    'Rejilla de Vapor': 'Steam Vent',
    'La caldera respira por aquí. No hace daño: solo hierve lo que llevas puesto.': 'The boiler breathes through here. It does no damage: it just boils what you are wearing.',
    'Rejilla de Escarcha': 'Frost Vent',
    'Un tubo de criogenia roto. El frío no mata: agrieta.': 'A broken cryogenic pipe. The cold does not kill: it cracks.',
    'Cuba de Ácido': 'Acid Vat',
    'Rebosa cada pocos segundos y se come el borde de la losa.': 'It overflows every few seconds and eats the edge of the slab.',
    'Chorro de Ácido': 'Acid Jet',
    'La válvula de la planta alta. Cuando salta, sale todo.': 'The valve from the floor above. When it blows, everything comes out.',

    /* ------------------------------------------------ pickups (data/resources.js) */
    'Residuo Alquímico': 'Alchemical Residue',
    '+5 de residuo.': '+5 residue.',
    'Un poso verde que baja por los desagües de toda la torre.': 'A green sediment that runs down every drain in the tower.',
    'Aceite Refrigerante': 'Coolant Oil',
    'Enfría 9 de calor en los seis injertos.': 'Cools 9 heat on all six grafts.',
    'Sabe a hierro y a taller. Los mecánicos lo bebían a escondidas.': 'It tastes of iron and workshop. The mechanics used to drink it in secret.',
    'Venda Grasienta': 'Greasy Bandage',
    'Recupera 8 de vida.': 'Restores 8 HP.',
    'Usada, pero del lado limpio.': 'Used, but on the clean side.',
    'Corazón en Salmuera': 'Heart in Brine',
    'Repara 14 de integridad en el miembro más dañado.': 'Repairs 14 integrity on the most damaged limb.',
    'Todavía late. Nadie sabe de quién era.': 'It is still beating. Nobody knows whose it was.',
    'Esquirla de Reloj': 'Clock Shard',
    '+1 esquirla para la tienda de la torre.': '+1 shard for the tower shop.',
    'Un trozo del reloj anatómico. Sigue contando algo.': 'A piece of the anatomical clock. It is still counting something.',

    /* --------------------------------------------- cosmetics (data/cosmetics.js) */
    'Carne Cruda': 'Raw Flesh',
    'La carne con la que llegaste. Nadie la eligió por ti.': 'The flesh you arrived in. Nobody chose it for you.',
    'Embalmado': 'Embalmed',
    'Formol, vendas apretadas y una sonrisa que ya no se mueve.': 'Formaldehyde, tight bandages and a smile that no longer moves.',
    'Carbonizado': 'Charred',
    'Salió del incendio de la planta baja y siguió andando.': 'It walked out of the ground floor fire and kept walking.',
    'Ahogado': 'Drowned',
    'Lo sacaron del depósito con los pulmones llenos de agua turbia.': 'They pulled it out of the tank with its lungs full of murky water.',
    'Fúngico': 'Fungal',
    'Algo crece debajo de la piel y respira por los poros.': 'Something grows under the skin and breathes through the pores.',
    'Cromado': 'Chromed',
    'Cada músculo sustituido por una pieza que brilla demasiado.': 'Every muscle replaced by a part that shines too much.',
    'Dorado': 'Gilded',
    'Los patronos pagan el oro. El cuerpo lo paga otro.': 'The patrons pay for the gold. Somebody else pays with the body.',
    'Espectral': 'Spectral',
    'La mitad de ti ya está en la sala de al lado.': 'Half of you is already in the next room.',

    /* ------------------------------------------- card vocabulary (render/scene-ui.js) */
    'Ataque': 'Attack',
    'Defensa': 'Block',
    'Habilidad': 'Skill',
    'Poder': 'Power',
    'Común': 'Common',
    'Poco común': 'Uncommon',
    'Rara': 'Rare',
    'Brazo': 'Arm',
    'Pierna': 'Leg',
    'Espinas': 'Thorns',
    'Regeneración': 'Regeneration',
    'Cartas extra': 'Extra cards',
    'Energía extra': 'Extra energy',
    'Bloqueo extra': 'Extra block',
    'Resiste calor': 'Heat resist',
    'Enfriamiento extra': 'Extra cooling',
    'Robavida': 'Lifesteal',
    'Golpe inicial': 'First strike',
    'Sangrado al golpear': 'Bleed on hit',
    'Vida máxima': 'Max HP',
    'Botín extra': 'Extra loot',
    'Mano inicial': 'Opening hand',
    'Sin pasiva': 'No passive',

    /* ------------------------------------------------ screens (render/scene-ui.js) */
    'El Reloj Anatómico': 'The Anatomical Clock',
    ' -Nivel ': ' -Tier ',
    'Nivel ': 'Tier ',
    'Integridad': 'Integrity',
    'Calor máx.': 'Max heat',
    'Enfriamiento': 'Cooling',
    'Vida': 'HP',
    'Pasiva: ': 'Passive: ',
    'CARTAS': 'CARDS',
    'INJERTO': 'GRAFT',
    'EL TIEMPO CORRE': 'THE CLOCK IS RUNNING',
    'No hay ningún injerto preparado.': 'No limb is ready to graft.',
    'El reloj no se detiene.': 'The clock does not stop.',
    'PIERDES': 'YOU LOSE',
    'GANAS': 'YOU GAIN',
    'Nada: el muñón.': 'Nothing: the stump.',
    ' cartas -': ' cards -',
    'CÓDICE ANATÓMICO': 'ANATOMICAL CODEX',
    'Planos': 'Blueprints',
    'Bestias': 'Beasts',
    'Ayuda': 'Help',
    'planos': 'blueprints',
    'bestias': 'beasts',
    'Flechas para mover -RETROCESO para volver': 'Arrows to move -BACKSPACE to go back',
    'Catálogo no disponible.': 'Catalogue unavailable.',
    'Un plano que aún no has arrancado\nde ningún cuerpo.': 'A blueprint you have not torn\noff any body yet.',
    'Todavía no la has visto de cerca. Mejor así.': 'You have not seen it up close yet. Just as well.',
    ' PV': ' HP',
    ' -JEFE': ' -BOSS',
    'TIENDA DE RELIQUIAS': 'RELIC SHOP',
    'EQUIPADO': 'EQUIPPED',
    'DISPONIBLE': 'AVAILABLE',
    'DESBLOQUEAR': 'UNLOCK',
    'BLOQUEADO': 'LOCKED',
    'Prototipo: la tienda no cobra dinero real y las esquirlas solo salen de la torre.': 'Prototype: the shop charges no real money and shards only come out of the tower.',
    'HAS MUERTO': 'YOU HAVE DIED',
    'La torre te ha desmontado pieza a pieza.': 'The tower took you apart piece by piece.',
    'SE ACABÓ EL TIEMPO': 'TIME IS UP',
    'El reloj anatómico se detuvo. Y tú con él.': 'The anatomical clock stopped. And you with it.',
    'HAS ESCAPADO': 'YOU HAVE ESCAPED',
    'Saliste por la puerta con el cuerpo que te queda.': 'You walked out of the gate with the body you had left.',
    'LA HUÍDA': 'THE ESCAPE',
    'Bajas': 'Kills',
    'Injertos': 'Grafts',
    'Miembros perdidos': 'Limbs lost',
    'Pisos superados': 'Floors cleared',
    'Tiempo restante': 'Time left',
    'Mejor huida': 'Best escape',
    'aún ninguna': 'none yet',
    'RECOMPENSAS': 'REWARDS',
    'Esquirlas': 'Shards',
    'Planos nuevos': 'New blueprints',
    'Bestias nuevas': 'New beasts',
    'Códice': 'Codex',
    ' planos': ' blueprints',
    'Carreras': 'Runs',
    'Huidas': 'Escapes',
    'Los planos que has arrancado se quedan en el códice. La torre, también.': 'The blueprints you tore out stay in the codex. So does the tower.',
    'Lo que has aprendido se queda en el códice. El cuerpo, no.': 'What you learned stays in the codex. The body does not.',
    'ENTER para volver al vestíbulo': 'ENTER to return to the lobby',
    'PAUSA': 'PAUSE',
    'ESC - Seguir jugando': 'ESC - Keep playing',

    /* ----------------------------------------------- help screen (render/scene-ui.js) */
    'EL RELOJ': 'THE CLOCK',
    'Tienes 360 segundos para todo: explorar, pelear y huir. El reloj corre también durante el combate, y no se detiene nunca. Cuando llega a cero, la torre te reclama.': 'You have 360 seconds for everything: exploring, fighting and fleeing. The clock runs during combat too, and it never stops. When it reaches zero, the tower claims you.',
    'EL CUERPO ES EL MAZO': 'THE BODY IS THE DECK',
    'No hay mazo aparte. Tus seis injertos son tus cartas: cabeza, torso, brazo izquierdo, brazo derecho, pierna izquierda y pierna derecha. Cada miembro aporta sus propias cartas, y una extremidad arrancada solo deja los golpes de muñón.': 'There is no separate deck. Your six grafts are your cards: head, torso, left arm, right arm, left leg and right leg. Each limb brings its own cards, and a limb that has been torn off leaves only the stump blows.',
    'EL CALOR': 'HEAT',
    'Cada carta calienta el miembro que la presta. El calor no baja solo: se enfría despacio mientras caminas. Si un injerto llega a su tope, pierde integridad, te quema y puede desprenderse. Jugar fuerte tiene un precio anatómico.': 'Every card heats the limb that lends it. Heat does not drop by itself: it cools slowly while you walk. If a graft reaches its cap it loses integrity, burns you and may tear off. Playing hard has an anatomical price.',
    'INJERTOS': 'GRAFTS',
    'Al matar a un enemigo puede caer un miembro. Recógelo y accede a la mesa de injerto: sustituirás el miembro de un hueco por el nuevo, con sus cartas y su pasiva. Los planos que descubras quedan en este códice para siempre, aunque mueras.': 'Killing an enemy may drop a limb. Pick it up and open the graft table: you swap the limb in one socket for the new one, with its cards and its passive. The blueprints you discover stay in this codex forever, even if you die.',
    'ALTARES Y RESIDUO': 'ALTARS AND RESIDUE',
    'El residuo alquímico se gasta en los altares para reparar integridad, enfriar el cuerpo o curarte. El aceite enfría, las vendas curan, y las esquirlas de reloj se guardan para la tienda.': 'Alchemical residue is spent at the altars to repair integrity, cool the body or heal you. Oil cools, bandages heal, and clock shards are kept for the shop.',
    'LA TORRE SE REORDENA': 'THE TOWER REARRANGES ITSELF',
    'Cada sesenta segundos el piso se vuelve a trazar a tu alrededor. La escalera y la salida siguen ahí, pero el camino no. Si la alarma suena, muévete.': 'Every sixty seconds the floor is redrawn around you. The stairs and the exit are still there, but the route is not. If the alarm sounds, move.',
    'ESCAPAR': 'ESCAPE',
    'Hay cuatro pisos. En los tres primeros, la escalera sube. En el último está la puerta de salida: llegar a ella con vida es la única victoria.': 'There are four floors. On the first three the stairs go up. On the last one is the exit gate: reaching it alive is the only victory.',

    /* ----------------------------------------------------- HUD (render/hud.js) */
    ' (muñón)': ' (stump)',
    'Cuerpo': 'Body',
    'Piso ': 'Floor ',
    '¡CALOR CRÍTICO! Un miembro va a estallar': 'CRITICAL HEAT! A limb is about to blow',

    /* ------------------------------------- card face tokens (render/scene-combat.js) */
    ' a todos': ' to all',
    ' daño': ' dmg',
    ' bloq': ' block',
    ' cartas': ' cards',
    ' energ.': ' energy',
    ' vida': ' HP',
    ' calor': ' heat',
    ' sangr.': ' bleed',
    ' débil': ' weak',
    ' frágil': ' frail',
    ' veneno': ' poison',
    ' aturde': ' stun',
    ' robo': ' leech',
    'desc. ': 'disc. ',
    'agota': 'exhaust',
    'bloq/calor': 'block/heat',
    'daño/calor': 'dmg/heat',
    'daño/muñón': 'dmg/stump',
    'botín': 'loot',
    'Robo': 'Draw',
    'Descarte': 'Discard',

    /* ------------------------------------------- exploration (render/scene-explore.js) */
    'no te quedes quieto': 'do not stand still',
    'sin mapa': 'no map',
    'ACTUAR': 'ACT',
    'E - Subir': 'E - Go up',
    'E - ESCAPAR': 'E - ESCAPE',
    'E - Usar altar': 'E - Use altar',
    'La torre aún no existe.': 'The tower does not exist yet.',

    /* ---------------------------------------------------------- run log (src/run.js) */
    'Te despiertas en una mesa de disección. Seis minutos.': 'You wake up on a dissection table. Six minutes.',
    '. El aire huele a formol.': '. The air smells of formaldehyde.',
    'La torre se reordena a tu alrededor.': 'The tower rearranges itself around you.',
    'Injertas ': 'You graft ',

    /* ------------------------------------------------------ scenes (src/scenes/) */
    'Aviso: horror corporal. Aquí se cosen miembros y se desmontan cuerpos.': 'Warning: body horror. Limbs are sewn on here and bodies are taken apart.',
    'Tienes seis minutos para escapar de la torre. El reloj no se detiene.': 'You have six minutes to escape the tower. The clock does not stop.',
    'PULSA CUALQUIER TECLA': 'PRESS ANY KEY',
    'NUEVA PARTIDA': 'NEW GAME',
    'CÓDIGO ANATÓMICO': 'ANATOMICAL CODEX',
    'TIENDA DE COSMÉTICOS': 'COSMETICS SHOP',
    'CÓMO JUGAR': 'HOW TO PLAY',
    'Carreras: ': 'Runs: ',
    '   Huidas: ': '   Escapes: ',
    '   Mejor huida: ': '   Best escape: ',
    '   Planos: ': '   Blueprints: ',
    'ENTER para elegir': 'ENTER to choose',
    'CONTINUAR': 'CONTINUE',
    'ABANDONAR LA TORRE': 'ABANDON THE TOWER',
    'El reloj no se detiene - quedan ': 'The clock does not stop - time left ',
    'CÓDICE': 'CODEX',
    'TAB códice - ESC pausa': 'TAB codex - ESC pause',
    'No hay ninguna partida en curso.': 'No run in progress.',
    'Despiertas en una mesa de disección. Seis minutos.': 'You wake on a dissection table. Six minutes.',
    'Dejas el miembro en el suelo. Se pierde.': 'You leave the limb on the floor. It is lost.',
    'ESC - Volver al vestíbulo': 'ESC - Back to the lobby',
    'ENTER: elegir - ESC: volver': 'ENTER: choose - ESC: back',

    /* ------------------------------------------------ combat log (systems/combat.js) */
    '¡': '',
    'No hay nada contra lo que luchar.': 'There is nothing to fight.',
    '¡Comienza el combate! ': 'The fight begins! ',
    'enemigo': 'enemy',
    'enemigos': 'enemies',
    ' inflige ': ' deals ',
    ' a ': ' to ',
    ' se levanta de nuevo!': ' gets back up!',
    ' cae desplomado.': ' collapses.',
    'Juegas ': 'You play ',
    'La hemorragia te cuesta ': 'The bleeding costs you ',
    ' de vida.': ' HP.',
    'El veneno te corroe: pierdes ': 'The poison eats at you: you lose ',
    'ataca': 'attacks',
    'se protege': 'braces',
    'se regenera': 'regenerates',
    'te maldice': 'curses you',
    'te marca': 'marks you',
    'se refuerza': 'steels itself',
    ' está aturdido y no llega a actuar.': ' is stunned and never gets to act.',
    'Turno ': 'Turn ',
    'Victoria. Recoges ': 'Victory. You collect ',
    ' de residuo.': ' residue.',
    'Entre los restos quedan ': 'Left among the remains: ',
    'miembro': 'limb',
    'miembros': 'limbs',
    'Tu cuerpo se apaga. El reloj sigue corriendo.': 'Your body shuts down. The clock keeps running.',
    'Escapas cojeando. El reloj no perdona.': 'You limp away. The clock does not forgive.',
    'No consigues escapar: pierdes ': 'You fail to escape: you lose ',

    /* ------------------------------------------------------- heat (systems/heat.js) */
    ' se sobrecalienta! Pierdes ': ' overheats! You lose ',
    ' se desprende y queda un muñón.': ' tears off and leaves a stump.',

    /* ------------------------------------------------ exploration (world/explore.js) */
    'Trampa': 'Trap',
    'Algo': 'Something',
    ' te corta el paso!': ' blocks your way!',
    'Restos en el suelo.': 'Remains on the floor.',
    'Un miembro cercenado.': 'A severed limb.',
    ' integridad': ' integrity',
    ' residuo': ' residue',
    ' aceite': ' oil',
    ' venda': ' bandage',
    ' esquirla': ' shard',
    'Hallazgo': 'Find',
    'El altar pide ': 'The altar asks for ',
    'Nada que reparar en tu cuerpo.': 'Nothing to repair on your body.',
    'El altar te devuelve ': 'The altar gives you back ',
    'El altar enfría tus miembros.': 'The altar cools your limbs.',
    'El altar repara ': 'The altar repairs '
  };

  var TABLES = { es: null, en: EN };

  /* ?lang=, then localStorage, then the browser, then Spanish. */
  function resolve() {
    var m = /[?&]lang=([a-zA-Z-]+)/.exec(String(window.location.search || ''));
    var q = m ? m[1].toLowerCase().substring(0, 2) : null;
    if (q === 'es' || q === 'en') return q;
    var saved = null;
    try { saved = window.localStorage.getItem('dd-lang'); } catch (e) { saved = null; }
    if (saved === 'es' || saved === 'en') return saved;
    var nav = String((window.navigator && window.navigator.language) || '').toLowerCase();
    return nav.indexOf('es') === 0 ? 'es' : 'es';
  }

  var active = resolve();
  var table = TABLES[active] || null;

  try { document.documentElement.lang = active; } catch (e) { /* ignore */ }

  /* index.html ships the Spanish title and description as the no-script
   * default; they are the only player-facing strings the tables cannot
   * reach, so they are swapped here at load. */
  if (active === 'en') {
    try {
      document.title = 'Deadlock Deck: The Anatomical Clock';
      var meta = document.querySelector('meta[name="description"]');
      if (meta) {
        meta.setAttribute('content',
          'Deadlock Deck: The Anatomical Clock - an anatomical deckbuilding roguelike.');
      }
    } catch (e) { /* ignore */ }
  }

  DD.LANGS = ['es', 'en'];

  DD.lang = function () { return active; };

  /* The exact Spanish literal in, the active language out. Anything the
   * dictionary does not know comes back unchanged. */
  DD.t = function (text) {
    if (!table || typeof text !== 'string') return text;
    var hit = table[text];
    return hit === undefined ? text : hit;
  };

  /* Stores the choice and reloads, because every table was translated once at
   * load time. A ?lang= already in the URL would outrank the stored value, so
   * it is rewritten rather than left to win. */
  DD.setLang = function (code) {
    if (code !== 'es' && code !== 'en') return;
    try { window.localStorage.setItem('dd-lang', code); } catch (e) { /* ignore */ }
    var href = String(window.location.href);
    if (/[?&]lang=/.test(href)) {
      window.location.href = href.replace(/([?&]lang=)[^&#]*/, '$1' + code);
      return;
    }
    window.location.reload();
  };
})();
